import eye from './eye.png';
import eye_slash from './eye-slash.png';
import gear from './gear.png';
import gear_fill from './gear-fill.png';
import heart from './heart-fill.png';
import house from './house.png';
import pause from './pause-fill.png';
import play from './play-fill.png';
import plus_circle from './plus-circle-fill.png';
import star from './star-fill.png';
import thumbs_down from './hand-thumbs-down.png';
import thumbs_up from './hand-thumbs-up.png';
import x_lg from './x-lg.png';

export const Eye = eye;
export const EyeSlash = eye_slash;
export const Gear = gear;
export const GearFill = gear_fill;
export const Heart = heart;
export const House = house;
export const Pause = pause;
export const Play = play;
export const PlusCircle = plus_circle;
export const Star = star;
export const ThumbsDown = thumbs_down;
export const ThumbsUp = thumbs_up;
export const XLg = x_lg;
